# top level project rules for the apq8064 project
#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := apq-touchpad

MODULES += app/aboot

DEBUG := 2

#DEFINES += WITH_DEBUG_DCC=1
#DEFINES += WITH_DEBUG_UART=1
DEFINES += WITH_DEBUG_FBCON=1
DEFINES += WITH_DEV_FBCON=1
DEFINES += DISPLAY_TYPE_TOUCHPAD=1
DEFINES += _EMMC_BOOT=1
DEFINES += DISABLE_MMC_DEBUG_SPEW
